In [ ]:
# Importing NumPy and printing version number
import numpy as np

print(np.__version__)



In [2]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])

c = a + b

print(c)

[[11 13 15]
 [17 19 21]]


In [3]:
a = np.array([[1,2,3],
              [4,5,6]])

b = 2*a # multiplying the numpy array a(matrix) by 2

print(b)

[[ 2  4  6]
 [ 8 10 12]]


In [4]:
#Create an identity matrix of dimension 4-by-4
i = np.eye(4)

print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
 #Convert a 1-D array to a 3-D array
a = np.array([x for x in range(27)])

o = a.reshape((3,3,3))

print(o)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [6]:
#Convert all the elements of a numpy array from float to integer datatype
a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])

o = a.astype('int')

print(o)

[[2 3 1]
 [4 2 1]]


In [7]:
#Convert a binary numpy array (containing only 0s and 1s) to a boolean numpy array
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]])

o = a.astype('bool')

print(o)

[[ True False False]
 [ True  True  True]
 [False False False]]


In [8]:
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

o = np.hstack((a1, a2))

print(o)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [9]:
a1 = np.array([[1,2],
               [3,4],
               [5,6]])

a2 = np.array([[7,8],
               [9,10],
               [10,11]])

o = np.vstack((a1, a2))

print(o)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [10 11]]


In [10]:
#sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers

list_of_numbers = [x for x in range(0, 101, 2)]

o = np.array(list_of_numbers)

print(o)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [11]:
o = np.linspace(0, 100, 5)   #gapped 5 number in range 0 to 100

print(o)

[  0.  25.  50.  75. 100.]


In [12]:
o = np.full((2, 3), 5)
print(o)


a = np.ones((2, 3))
o = 5*a
print(o)


[[5 5 5]
 [5 5 5]]
[[5. 5. 5.]
 [5. 5. 5.]]


In [13]:
#Output a 5-by-5 array of random integers between 0 (inclusive) and 10 (exclusive)
np.random.seed(123) # setting the seed

o = np.random.randint(0, 10, size = (5,5))

print(o)

[[2 2 6 1 3]
 [9 6 1 0 1]
 [9 0 0 9 3]
 [4 0 0 4 1]
 [7 3 2 4 7]]


In [14]:
#Output a 3-by-3 array of random numbers following normal distribution
np.random.seed(123) # setting the seed

o = np.random.normal(size = (3,3))

print(o)

[[-1.0856306   0.99734545  0.2829785 ]
 [-1.50629471 -0.57860025  1.65143654]
 [-2.42667924 -0.42891263  1.26593626]]


In [15]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])

o = a@b

print(o)

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


In [17]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

a_transpose = a.T

print(a_transpose)  #Matrix Transpose

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [18]:
in_arr = np.array([2, 0, 1, 5, 4, 1, 9])
print("Input unsorted array : ", in_arr)
 
out_arr = np.argsort(in_arr)
print("Output sorted array indices : ", out_arr)
print("Output sorted array : ", in_arr[out_arr])

Input unsorted array :  [2 0 1 5 4 1 9]
Output sorted array indices :  [1 2 5 0 4 3 6]
Output sorted array :  [0 1 1 2 4 5 9]


In [ ]:
# Mathematics: np.sum, np.exp, np.round, arithemtic operators
# Array manipulation: np.reshape, np.stack, np.concatenate, np.split
# Linear Algebra: np.matmul, np.dot, np.transpose, np.eigvals
# Statistics: np.mean, np.median, np.std, np.max


In [22]:
import numpy as np

arr1 = np.array([[1, 6, 7, 4], 
                 [5, 3, 7, 8], 
                 [6, 7, 2, 9]])

arr2 = np.array([[11, 17, 17, 14], 
                 [15, 16, 19, 18], 
                 [14, 11, 11, 13]])


In [23]:
arr1 + arr2

array([[12, 23, 24, 18],
       [20, 19, 26, 26],
       [20, 18, 13, 22]])

In [24]:
arr1 * arr2


array([[ 11, 102, 119,  56],
       [ 75,  48, 133, 144],
       [ 84,  77,  22, 117]])

In [25]:
arr1 + 5

array([[ 6, 11, 12,  9],
       [10,  8, 12, 13],
       [11, 12,  7, 14]])

In [26]:
arr1 / arr2


array([[0.09090909, 0.35294118, 0.41176471, 0.28571429],
       [0.33333333, 0.1875    , 0.36842105, 0.44444444],
       [0.42857143, 0.63636364, 0.18181818, 0.69230769]])

In [27]:
arr1 % 5

array([[1, 1, 2, 4],
       [0, 3, 2, 3],
       [1, 2, 2, 4]])

In [28]:
arr2

array([[11, 17, 17, 14],
       [15, 16, 19, 18],
       [14, 11, 11, 13]])

In [30]:
arr3 =np.array([4,5,6,8])

In [31]:
arr3.shape

(4,)

In [33]:
arr1 == arr2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [34]:
(arr1 == arr2).dtype


dtype('bool')

In [35]:
arr1 != arr2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [36]:
arr1 >= arr2


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [41]:
arr4 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

arr4.shape

(3, 2, 4)

In [42]:
arr4[1,1,2]

np.float64(36.0)

In [43]:
# subarray using ranges

arr4[1:,0:1,:2]

array([[[15., 16.]],

       [[98., 32.]]])

In [44]:
# mixing indicies and ranges
arr4[1:,1,:3]

array([[63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [45]:
np.zeros((3,2))


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [46]:

# All ones
np.ones([2, 2, 3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [47]:

np.eye(3)    # Identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
np.full([2, 3], 26)  #fixed value


array([[26, 26, 26],
       [26, 26, 26]])

In [53]:
np.arange(10,90,3).reshape(3,3,3)


array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [54]:
np.sin(np.pi/2.)


np.float64(1.0)